name = "webapp"
compatibility_date = "2025-12-10"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "mafia-stream-db"
database_id = ""
